# a list of distinct broker names
brokers:
  - broker1
  - broker2
<<<<<<< HEAD

# a list of topics that declare how many sensors push to it
sensors:
  - topic: topic1
    nb: 3
    broker: broker1
  - topic: topic2
    nb: 3
    broker: broker2
=======
  - logBroker

# a list of topics that declare how many sensors push to it
sensors:
  - broker: broker1
    topic: topic1
    nb: 3
    # MQTT broker that sensors can log to, you can declare them above 
    remoteLoggingBroker: 
      host: logBroker
      port: 1883
      topic: logging
      username: xxx
      password: xxx
    
  - broker: broker2
    topic: topic2
    nb: 3
    remoteLoggingBroker:
      host: logBroker
      port: 1883
      topic: logging
      username: xxx
      password: xxx
    
>>>>>>> cf2a084da5f96bbcb85c514781a0e9c861775c32

# a list of ingestion clients that read from selected brokers and their topics
ingestionClients:
  - brokers:
      - brokerId: broker1
        topics: 
          - topic1
<<<<<<< HEAD
=======
    data: default # data plugin to use for ingestionClient
>>>>>>> cf2a084da5f96bbcb85c514781a0e9c861775c32
    
  - brokers:
      - brokerId: broker2
        topics: 
          - topic2
<<<<<<< HEAD
=======
    data: default
>>>>>>> cf2a084da5f96bbcb85c514781a0e9c861775c32

# the location of the data file as a .csv
# also specifies which of the columns corresponds to the ID of the sensor
data:
  path: './data.csv'
  sensorId: 'station_id'


<<<<<<< HEAD
=======
# configuration for the bigQuery dataplugin, check the ingestion client
bigQuery:
  name: myDataset
  tables:
    - id: testTable1
      topics: # the topics that contain information to be stored on this table
        - topic1
        - topic2
      # https://cloud.google.com/bigquery/docs/schemas for all BigQuery datatypes and schema definition
      schema:
        - description: description of field
          mode: REQUIRED
          name: id
          type: STRING

        - description: description of field
          mode: REQUIRED
          name: value
          type: FLOAT
>>>>>>> cf2a084da5f96bbcb85c514781a0e9c861775c32

